import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { Nunito, Nunito_Sans } from "next/font/google";
import "./globals.css";
import { ExitModal } from "@/components/Modals/ExitModal";
import { HeartsModal } from "@/components/Modals/HeartsModal";
import { PracticeModal } from "@/components/Modals/PracticeModal";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signInUrl="/learn"
      signUpUrl="/learn"
      afterSignOutUrl="/learn"
    >
      <html lang="en">
        <body
          className={`${nunitoSans.variable} ${nunito.variable} antialiased`}
        >
          <Toaster />
          <HeartsModal />
          <PracticeModal />
          <ExitModal />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
